drop table IF EXISTS SURVEYRS;
drop table IF EXISTS INITIALBEHAVIOR;
drop table IF EXISTS FINALBEHAVIOR;
drop table IF EXISTS PHASE1;
drop table IF EXISTS PHASE2;
drop table IF EXISTS PHASE3;
drop table IF EXISTS PHASE4;
drop table IF EXISTS USERS;
drop table IF EXISTS LOGINS;

CREATE TABLE LOGINS
(
USERID varchar(60) NOT NULL,
PASSWORD varchar(255),
ROLE varchar(255),
DATE DATE,
PRIMARY KEY(USERID)
)
ENGINE=InnoDB;

CREATE TABLE USERS
(
USERID varchar(60) NOT NULL,
PHASE1 boolean,
PHASE2 boolean,
PHASE3 boolean,
PHASE4 boolean,
PHASEP boolean,
PRIMARY KEY(USERID),
FOREIGN KEY(USERID) 
	REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE SURVEYRS
(
SURVEYID int NOT NULL AUTO_INCREMENT,
USERID varchar(60) NOT NULL,
DATETIME datetime,
Q1 int,
Q2 int,
Q3 int,
Q4 int,
Q5 int,
Q6 int,
Q7 int,
Q8 int,
Q9 int,
Q10 int,
PRIMARY KEY(SURVEYID),
FOREIGN KEY(USERID) 
	REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE INITIALBEHAVIOR
(
USERID varchar(60) NOT NULL,
DATETIME datetime,
TASKR int NOT NULL,
PRIMARY KEY(USERID),
FOREIGN KEY(USERID) 
	REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE FINALBEHAVIOR
(
USERID varchar(60) NOT NULL,
DATETIME datetime,
TASKR int NOT NULL,
PRIMARY KEY(USERID),
FOREIGN KEY(USERID) REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE PHASE1
(
SESSIONID int NOT NULL AUTO_INCREMENT,
USERID varchar(60) NOT NULL,
DATETIME datetime,
R1 int,
R2 int,
R3 int,
R4 int,
R5 int,
R6 int,
R7 int,
R8 int,
R9 int,
R10 int,
PRIMARY KEY(SESSIONID),
FOREIGN KEY(USERID) REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE PHASE2
(
SESSIONID int NOT NULL AUTO_INCREMENT,
USERID varchar(60) NOT NULL,
DATETIME datetime,
R1 int,
R2 int,
R3 int,
R4 int,
R5 int,
R6 int,
R7 int,
R8 int,
R9 int,
R10 int,
PRIMARY KEY(SESSIONID),
FOREIGN KEY(USERID) REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE PHASE3
(
SESSIONID int NOT NULL AUTO_INCREMENT,
USERID varchar(60) NOT NULL,
DATETIME datetime,
R1 int,
R2 int,
R3 int,
R4 int,
R5 int,
R6 int,
R7 int,
R8 int,
R9 int,
R10 int,
PRIMARY KEY(SESSIONID),
FOREIGN KEY(USERID) REFERENCES LOGINS(USERID) ON DELETE CASCADE) 
ENGINE=InnoDB;

CREATE TABLE PHASE4
(
SESSIONID int NOT NULL AUTO_INCREMENT,
USERID varchar(60) NOT NULL,
DATETIME datetime,
R1 int,
R2 int,
R3 int,
R4 int,
R5 int,
R6 int,
R7 int,
R8 int,
R9 int,
R10 int,
PRIMARY KEY(SESSIONID),
FOREIGN KEY(USERID) REFERENCES LOGINS(USERID) ON DELETE CASCADE)
ENGINE=InnoDB;
